services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: testdb
            MONGO_INITDB_USERNAME: testuser
            MONGO_INITDB_PASSWORD: testpassword
        ports:
            - 27017:27017
        volumes:
            # - mongo_data:/data/db
            - ./init-mongo.js:/docker-entrypoint-initdb.d/inits-mongo.js:ro # Mount initialization script

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
            ME_CONFIG_BASICAUTH: false
# volumes:
#     mongo_data:
#         driver: local
